/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paralelo;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author rosal
 */
public class Principal extends javax.swing.JFrame
{

    static long inicio_tiempo = 0;

    /**
     * Creates new form NewJFrame
     */
    public Principal()
    {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        TextField_n = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextField_min = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextField_max = new javax.swing.JTextField();
        Button_Iniciar = new javax.swing.JButton();
        Button_Reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        TextField_Conjunto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextField_Subconjuntos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TextField_Tiempo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Resultados = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Panel_Subconjuntos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sumar subconjuntos");

        jPanel1.setBackground(new java.awt.Color(204, 186, 184));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 128, 125)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 50));

        TextField_n.setBackground(new java.awt.Color(250, 250, 250));
        TextField_n.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextField_n.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                TextField_nKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("n");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("min");

        TextField_min.setBackground(new java.awt.Color(250, 250, 250));
        TextField_min.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextField_min.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                TextField_minKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("max");

        TextField_max.setBackground(new java.awt.Color(250, 250, 250));
        TextField_max.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextField_max.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                TextField_maxKeyTyped(evt);
            }
        });

        Button_Iniciar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Button_Iniciar.setText("iniciar");
        Button_Iniciar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button_IniciarActionPerformed(evt);
            }
        });

        Button_Reset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Button_Reset.setText("reset");
        Button_Reset.setEnabled(false);
        Button_Reset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_n, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_min, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_max, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Button_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(Button_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_n, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_min, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_max, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 186, 184));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 128, 125)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 50));

        TextField_Conjunto.setEditable(false);
        TextField_Conjunto.setBackground(new java.awt.Color(240, 240, 240));
        TextField_Conjunto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Conjunto");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("No. subconjuntos");

        TextField_Subconjuntos.setEditable(false);
        TextField_Subconjuntos.setBackground(new java.awt.Color(240, 240, 240));
        TextField_Subconjuntos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_Conjunto)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_Subconjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Conjunto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Subconjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 186, 184));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 128, 125)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tiempo total de ejecución");

        TextField_Tiempo.setEditable(false);
        TextField_Tiempo.setBackground(new java.awt.Color(240, 240, 240));
        TextField_Tiempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("segundos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 186, 184));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 128, 125)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 100));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 310));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 310));

        TextArea_Resultados.setEditable(false);
        TextArea_Resultados.setBackground(new java.awt.Color(240, 240, 240));
        TextArea_Resultados.setColumns(10);
        TextArea_Resultados.setRows(5);
        TextArea_Resultados.setTabSize(0);
        jScrollPane1.setViewportView(TextArea_Resultados);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Resultados");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subconjuntos");

        jScrollPane3.setBorder(null);
        jScrollPane3.setOpaque(false);

        Panel_Subconjuntos.setBackground(new java.awt.Color(204, 186, 184));
        Panel_Subconjuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 128, 125)));
        Panel_Subconjuntos.setLayout(new javax.swing.BoxLayout(Panel_Subconjuntos, javax.swing.BoxLayout.X_AXIS));
        jScrollPane3.setViewportView(Panel_Subconjuntos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void Button_IniciarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Button_IniciarActionPerformed
    {//GEN-HEADEREND:event_Button_IniciarActionPerformed
        if (datos_correctos())
        {
            Button_Iniciar.setEnabled(false);

            inicio_tiempo = System.nanoTime();

            int n = Integer.parseInt(TextField_n.getText().trim());
            int min = Integer.parseInt(TextField_min.getText().trim());
            int max = Integer.parseInt(TextField_max.getText().trim());

            int conjunto[] = genera_conjunto(n, min, max);
            TextField_Conjunto.setText(Arrays.toString(conjunto));

            TextField_Subconjuntos.setText(String.valueOf(total_subconjuntos((long) n)));

            for (int r = n; r >= 2; r--)
            {
                javax.swing.JTextArea ta = new JTextArea("Subconjuntos con " + r + " elementos\n\n");
                ta.setEditable(false);
                ta.setBackground(new Color(240, 240, 240));
                Panel_Subconjuntos.add(ta);
                Panel_Subconjuntos.updateUI();
                Thread t = new sumar_subconjuntos(TextArea_Resultados, ta, conjunto, r);
                t.start();
            }

        } else
        {
            JOptionPane.showMessageDialog(this, "Verifique los datos ingresados:\nn(mayor a 2)\nmin (negativo)\nmax (positivo)");
        }
    }//GEN-LAST:event_Button_IniciarActionPerformed


    private void Button_ResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Button_ResetActionPerformed
    {//GEN-HEADEREND:event_Button_ResetActionPerformed
        TextField_n.setText("");
        TextField_min.setText("");
        TextField_max.setText("");
        TextField_Conjunto.setText("");
        TextField_Subconjuntos.setText("");
        TextField_Tiempo.setText("");
        TextArea_Resultados.setText("");
        Panel_Subconjuntos.removeAll();
        Panel_Subconjuntos.updateUI();
        Button_Iniciar.setEnabled(true);
        Button_Reset.setEnabled(false);
    }//GEN-LAST:event_Button_ResetActionPerformed

    private void TextField_nKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TextField_nKeyTyped
    {//GEN-HEADEREND:event_TextField_nKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9')
        {
            evt.setKeyChar((char) 8);
        }
    }//GEN-LAST:event_TextField_nKeyTyped

    private void TextField_maxKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TextField_maxKeyTyped
    {//GEN-HEADEREND:event_TextField_maxKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9')
        {
            evt.setKeyChar((char) 8);
        }
    }//GEN-LAST:event_TextField_maxKeyTyped

    private void TextField_minKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TextField_minKeyTyped
    {//GEN-HEADEREND:event_TextField_minKeyTyped
        if ((evt.getKeyChar() < '0' || evt.getKeyChar() > '9') && evt.getKeyChar() != '-')
        {
            evt.setKeyChar((char) 8);
        }
    }//GEN-LAST:event_TextField_minKeyTyped

    private boolean datos_correctos()
    {
        boolean b = false;
        try
        {
            if ((Integer.parseInt(TextField_n.getText().trim())) > 2)
            {
                if (Integer.parseInt(TextField_min.getText().trim()) < 0)
                {
                    if (Integer.parseInt(TextField_max.getText().trim()) > 0)
                    {
                        b = true;
                    }
                }
            }
        } catch (Exception e)
        {
            System.out.println("Error de validación");
        }
        return b;
    }

    private int[] genera_conjunto(int n, int min, int max)
    {
        int conjunto[] = new int[n];
        for (int i = 0; i < n; i++)
        {
            conjunto[i] = (int) (Math.random() * (max - min + 1) + min);
        }
        return conjunto;
    }

    private long total_subconjuntos(long n)
    {
        long suma = 0;
        for (long r = n; r >= 2; r--)
        {
            long combinaciones = factorial(n) / (factorial(n - r) * factorial(r));
            System.out.println(combinaciones + " subconjuntos encontrados con " + r + " elementos");
            suma += combinaciones;
        }
        return suma;
    }

    private long factorial(long f)
    {
        if (f == 0)
        {
            return 1;
        } else
        {
            return f * factorial(f - 1);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Principal().setVisible(true);
            }
        });
    }

    public static double tiempo(long inicio, long fin)
    {
        return (double) ((((double) fin) - ((double) inicio)) / 1000000000);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Iniciar;
    public static javax.swing.JButton Button_Reset;
    private javax.swing.JPanel Panel_Subconjuntos;
    public static javax.swing.JTextArea TextArea_Resultados;
    private javax.swing.JTextField TextField_Conjunto;
    private javax.swing.JTextField TextField_Subconjuntos;
    public static javax.swing.JTextField TextField_Tiempo;
    private javax.swing.JTextField TextField_max;
    private javax.swing.JTextField TextField_min;
    private javax.swing.JTextField TextField_n;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
